name: mnotes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  simple_shadow: ^0.3.1
  flash: ^3.0.5+1
  url_launcher: ^6.1.12
  equatable: ^2.0.5
  dio: ^4.0.6
  email_validator: ^2.1.17
  flutter_secure_storage: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
        - asset: fonts/Oxygen-Light.ttf
        - asset: fonts/Oxygen-Regular.ttf
  assets: 
    - assets/icons/google_icon.svg
    - assets/icons/facebook_icon.svg
    - assets/icons/apple_icon.svg
    - assets/icons/back_icon.svg
    - assets/icons/success_icon.svg
    - assets/icons/error_icon.svg
    - assets/icons/save_icon.svg
    - assets/icons/home_chat_icon.svg
    - assets/icons/home_settings_icon.svg
    - assets/icons/home_contacts_icon.svg
    - assets/icons/home_ellipse_icon.svg
    - assets/icons/home_search_icon.svg
    - assets/icons/home_notes_icon.png
    - assets/icons/home_mnotes_icon.svg
    - assets/icons/contacts_details_phone_icon.svg
    - assets/icons/contacts_details_edit_icon.svg
    - assets/icons/settings_go_icon.svg
    - assets/icons/settings_person_icon.svg
    - assets/icons/settings_lock_icon.svg
    - assets/icons/settings_password_icon.svg
    - assets/icons/settings_email_icon.svg
    - assets/icons/settings_contact_icon.svg
    - assets/icons/settings_microphone_icon.svg
    - assets/icons/settings_camera_icon.svg
    - assets/backgrounds/lets_start.svg
    - assets/backgrounds/contacts_permission.png