name: mnotes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  simple_shadow: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
        - asset: fonts/Oxygen-Light.ttf
        - asset: fonts/Oxygen-Regular.ttf
  assets: 
    - images/google_icon.svg
    - images/facebook_icon.svg
    - images/apple_icon.svg
    - images/back_icon.svg